druid:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springmvc?useSSL=false
  username: root
  password: 690818
  initialSize: 10
  minIdle: 6
  maxActive: 50
  maxWait: 60000
  timeBetweenConnectErrorMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: wall,stat





